### ISSUE TITLE
Android not displaying push notification when app is swiped off

### ISSUE THREAD

**Issue by pantelistsakoulis-ts** [exponea/exponea-flutter-sdk#11]
Due to the update of the native android SDK the push notifications when the app is swiped off are no longer being displayed until the app is manually opened.

This happens due to the SDK not auto initializing anymore.

I will create a PR that exposes some methods that allow 3rd party users to check the internal state of the Exponea SDK.

**Comment by adam1929** [comment]
Thank you @pantelistsakoulis-ts for your PR.
Downside if SDK init while RemoteMessage handling is, that SDK initialisation does also fetching of data that are not needed in that case. Also keep in mind, that Android gives a time around 10s to finish a work for tracking and notif-showing process.
If SDK init will take more time, tracking of notification data and showing notification (plus downloading image) may not been finished, OS will kill your process.
Also, in case that your process survives it (ie user click on push so app goes to foreground), you are not able to initialize SDK second time = that may be an issue in case of App update or conditional SDK configuration with different result that is stored (as is PR written).
Currently, Android SDK 3.5.0 handles this process with "partial" initialization and will be included in next Flutter SDK release.

**Comment by pantelistsakoulis-ts** [comment]
Hi @adam1929 

Thanks for the update, could you provide me an approximate date for the next release for the plugin update?
