### ISSUE TITLE
Method channel error

### ISSUE THREAD

**Issue by omegasoft7** [exponea/exponea-flutter-sdk#13]
Currently when we are sending some events, after sending a couple of events we are seeing this log in our console:

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(ExponeaPlugin, Invalid type for value in data 'NSNull'., null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      MethodChannelExponeaPlatform.trackEvent (package:exponea/src/platform/method_channel.dart:126:5)
<asynchronous suspension>

Not sure it was unable to send events or if some events were missing some information. But will just put it here for your reference

**Comment by adam1929** [comment]
Hi @omegasoft7 may you please describe your usage? You are sending customised events (tracking manually) or this error is caused from SDK internal triggers?
From logs, I can only see that Flutter is running on iOS device and method `trackEvent` is trying to handle some NIL value. Please validate my thoughts, if this scenario is possible. Thank you

**Comment by adam1929** [comment]
@omegasoft7 Hi, we bring a NIL handling in native iOS so next Flutter release will have this handling also. Thank you for reporting

**Comment by xcibik00** [comment]
Hi @omegasoft7 , we already released new Flutter version 1.5.0 which contains newest iOS SDK 2.21.3, fix for this was in 2.17.0 - so it should be OK.
