### ISSUE TITLE
Android SDK release build failed

### ISSUE THREAD

**Issue by mishaAe** [exponea/exponea-flutter-sdk#14]
Trying to build prod build and get error 
`
ERROR:/Users/mikhailvasilev/.gradle/caches/transforms-3/cc5eade814f67f35bebc86d29d898212/transformed/jetified-sdk-3.6.1-runtime.jar: R8: Type com.exponea.style.AppInboxListViewStyle is defined multiple times: /Users/mikhailvasilev/.gradle/caches/transforms-3/cc5eade814f67f35bebc86d29d898212/transformed/jetified-sdk-3.6.1-runtime.jar:com/exponea/style/AppInboxListViewStyle.class, /Users/mikhailvasilev/NK/novakid-mobile/build/exponea/intermediates/runtime_library_classes_jar/release/classes.jar:com/exponea/style/AppInboxListViewStyle.class`

**Comment by mishaAe** [comment]
fix: remove implementation 'com.exponea.sdk:sdk:3.6.1' from app/build.gradle

**Comment by adam1929** [comment]
Hi @mishaAe what is your setup? Flutter SDK includes Android SDK 3.5.0, not 3.6.1 😮 
Second 'fix' comment is unclear to me. Are we suppose to change something? Of course we are not using 3.6.1 here, so I'm still confused. Thank you for your explanation.
