### ISSUE TITLE
AppInboxProvider not visible on iOS

### ISSUE THREAD

**Issue by bshv-ciklum** [exponea/exponea-flutter-sdk#16]
`AppInboxProvider` Widget is not visible on iOS platform.
When I try to display the widget I get an error:
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(unregistered_view_type, A UIKitView widget is trying to create a PlatformView with an unregistered type: < FluffView >, If you are the author of the PlatformView, make sure `registerViewFactory` is invoked.
See: https://docs.flutter.dev/development/platform-integration/platform-views#on-the-platform-side-1 for more details.
```

Fix PR: https://github.com/exponea/exponea-flutter-sdk/pull/15

**Comment by roland-misica** [comment]
Hi, we tested that and reproduced it on our side as well. The proposed PR fixes the issue. We are closing it for now and the fix will be available in the next release. Thanks.
