### ISSUE TITLE
Update native sdk versions

### ISSUE THREAD

**Issue by we-chintan-p001** [exponea/exponea-flutter-sdk#18]
Hi,

can someone update native sdk versions for this package?

**Comment by we-prajapati-c001** [comment]
Thanks for the reply @roland-misica If you can check
https://github.com/exponea/exponea-flutter-sdk/blob/main/android/build.gradle#L9
https://github.com/exponea/exponea-flutter-sdk/blob/main/ios/exponea.podspec#L18

Can you also check if you can upgrade `androidx.work:work-runtime`?

**Comment by roland-misica** [comment]
Thanks for the clarification,
We will update native SDKs in the next release, as we are providing new features and bug fixes.
We will take a look if we can upgrade `androidx.work:work-runtime`

Regards

**Comment by xcibik00** [comment]
Hi @we-prajapati-c001, we already released 1.5.0 which includes native Exponea iOS SDK 2.21.3 and Android 3.11.2

**Comment by we-prajapati-c001** [comment]
Thanks @xcibik00!
