### ISSUE TITLE
AppStore Connect: Invalid Privacy Info

### ISSUE THREAD

**Issue by LarssK-TS** [exponea/exponea-flutter-sdk#27]
Hi, we have started receiving emails from AppStore Connect everytime we upload a new build, the app hasn't been rejected but it sounds like apps will be rejected after November 12th 2024. The issue appears to be related to the Exponea SDK missing the declaration, manifest and tracking information in the privacyinfo file.

> Although submission for App Store review was successful, you may want to correct the following issues in your next submission for App Store review. Once you've corrected the issues, upload a new binary to App Store Connect.
> 
> ITMS-91106: Invalid API reason declaration - The PrivacyInfo.xcprivacy file at the “Frameworks/ExponeaSDK_Notifications.framework/ExponeaSDK-Notifications.bundle/PrivacyInfo.xcprivacy” path contains “C617.1” as the value for a NSPrivacyAccessedAPITypeReasons key instead of a valid reason code for using an API in the NSPrivacyAccessedAPICategoryUserDefaults category. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. Values for NSPrivacyAccessedAPITypeReasons keys in any privacy manifest must be valid reason codes for the corresponding API category. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91108: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/Reachability.framework/ReachabilitySwift.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk.
> 
> ITMS-91107: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/ExponeaSDK_Notifications.framework/ExponeaSDK-Notifications.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. Keys and values in any privacy manifest must be valid. For more details, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk.

Reading the docs Apple has a work around for users who aren't able to obtain  a valid manifest from 3rd party SDK developers, however I'm not sure what will happen come November 12th. https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk#4477106

Thank you

**Comment by xcibik00** [comment]
Hi @LarssK-TS , I double-checked it and as I mentioned, it was fixed in native iOS [2.26.2](https://github.com/exponea/exponea-ios-sdk/commit/80252e93c6b67906587d99db1af776a2c1819ffb) so it should work for Exponea Flutter SDK 1.7.0 +

But based on the info ^ "“Frameworks/ExponeaSDK_Notifications.framework/ExponeaSDK-Notifications.bundle" , its a problem with Exponea SDK Notification part -> which is not directly part of Flutter SDK, and you are linking it in app notification extension - and also this must be version 2.26.2+ (we recommend to use the same version as iOS SDK is used (so for Flutter 1.7.0 is 2.28.0 as you can see [here](https://github.com/exponea/exponea-flutter-sdk/blob/main/ios/exponea.podspec)))

Can you please check you ExponeaSDK-Notifications version you are using in the app? -> and update it to at least 2.26.2 (resp. to 2.28.0)

With that version it should be fine 🙏

**Comment by LarssK-TS** [comment]
> Hi @LarssK-TS , I double-checked it and as I mentioned, it was fixed in native iOS [2.26.2](https://github.com/exponea/exponea-ios-sdk/commit/80252e93c6b67906587d99db1af776a2c1819ffb) so it should work for Exponea Flutter SDK 1.7.0 +
> 
> But based on the info ^ "“Frameworks/ExponeaSDK_Notifications.framework/ExponeaSDK-Notifications.bundle" , its a problem with Exponea SDK Notification part -> which is not directly part of Flutter SDK, and you are linking it in app notification extension - and also this must be version 2.26.2+ (we recommend to use the same version as iOS SDK is used (so for Flutter 1.7.0 is 2.28.0 as you can see [here](https://github.com/exponea/exponea-flutter-sdk/blob/main/ios/exponea.podspec)))
> 
> Can you please check you ExponeaSDK-Notifications version you are using in the app? -> and update it to at least 2.26.2 (resp. to 2.28.0)
> 
> With that version it should be fine 🙏

That makes sense I will double check, I will double check.
