### ISSUE TITLE
Cannot upgrade gradle (AGP) because namespace in module's build.gradle isn't specified

### ISSUE THREAD

**Issue by VeesileNavi** [exponea/exponea-flutter-sdk#29]
A problem occurred configuring project ':exponea'.

Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

Since 8 version gradle requires to define namespace property like this:

(groovy)
if (project.android.hasProperty("namespace")) {
        namespace '<appname>'
    }

or

namespace '<appname>'

**Comment by xcibik00** [comment]
Hi @VeesileNavi - already addressed and answered https://github.com/exponea/exponea-flutter-sdk/pull/28#issuecomment-2500594379

**Comment by xcibik00** [comment]
Hi @VeesileNavi we added Gradle 8 support in 2.0.0 SDK version

**Comment by VeesileNavi** [comment]
> Hi @VeesileNavi we added Gradle 8 support in 2.0.0 SDK version

Hi!
Thanks for notifying, we will integrate it as soon as possible👍
