### ISSUE TITLE
 Flush mode is not manual

### ISSUE THREAD

**Issue by maxim-ivanchuk-idf** [exponea/exponea-flutter-sdk#3]
{"exception":{"values":[{"stacktrace":{"frames":[{"package":"app","abs_path":"app/base/bloc.dart","colno":7,"filename":"bloc.dart","function":"BlocImpl.launchPayload","in_app":true,"lineno":265,"unknown":{"package":"app"}},{"abs_path":"<asynchronous suspension>"},{"package":"app","abs_path":"app/base/bloc.dart","colno":7,"filename":"bloc.dart","function":"BlocImpl.logout.<fn>","in_app":true,"lineno":149,"unknown":{"package":"app"}},{"abs_path":"<asynchronous suspension>"},{"package":"app","abs_path":"app/internal/services/exponea_service.dart","colno":5,"filename":"exponea_service.dart","function":"_AppExponeaService.flush","in_app":true,"lineno":141,"unknown":{"package":"app"}},{"abs_path":"<asynchronous suspension>"},{"package":"exponea","abs_path":"package:exponea/src/platform/method_channel.dart","colno":5,"filename":"method_channel.dart","function":"MethodChannelExponeaPlatform.flushData","in_app":true,"lineno":99,"unknown":{"package":"exponea"}},{"abs_path":"<asynchronous suspension>"},{"package":"flutter","abs_path":"package:flutter/src/services/platform_channel.dart","colno":18,"filename":"platform_channel.dart","function":"MethodChannel._invokeMethod","in_app":false,"lineno":156,"unknown":{"package":"flutter"}},{"package":"flutter","abs_path":"package:flutter/src/services/message_codecs.dart","colno":7,"filename":"message_codecs.dart","function":"StandardMethodCodec.decodeEnvelope","in_app":false,"lineno":607,"unknown":{"package":"flutter"}}]},"type":"PlatformException","value":"PlatformException(ExponeaPlugin, Flush mode is not manual., null, null)"}]},"modules":{"StackWalker":"unknown","_fe_analyzer_shared":"unknown","aFileChooser":"unknown","abseil-cpp":"unknown","accessibility":"unknown","skia":"unknown","angle":"unknown","boringssl":"unknown","etc1":"unknown","khronos":"unknown","libwebp":"unknown","txt":"unknown","vulkan":"unknown","vulkan-deps":"unknown","wuffs":"unknown","base":"unknown","fuchsia_sdk":"unknown","zlib":"unknown","icu":"unknown","engine":"unknown","gpu":"unknown","image_picker":"unknown","tonic":"unknown","url_launcher_web":"unknown","analyzer":"unknown","rapidjson":"unknown","xxhash":"unknown","appsflyer_sdk":"unknown","args":"unknown","csslib":"unknown","logging":"unknown","async":"unknown","cli_util":"unknown","boolean_selector":"unknown","dart":"unknown","build":"unknown","build_runner":"unknown","code_builder":"unknown","web_socket_channel":"unknown","build_config":"unknown","graphs":"unknown","io":"unknown","build_daemon":"unknown","ffi":"unknown","package_config":"unknown","build_resolvers":"unknown","build_runner_core":"unknown","pubspec_parse":"unknown","test_api":"unknown","built_collection":"unknown","built_value":"unknown","characters":"unknown","checked_yaml":"unknown","charcode":"unknown","fixnum":"unknown","http_parser":"unknown","matcher":"unknown","path":"unknown","pool":"unknown","shelf_web_socket":"unknown","source_span":"unknown","stack_trace":"unknown","string_scanner":"unknown","yaml":"unknown","chewie":"unknown","chewie_audio":"unknown","clock":"unknown","fake_async":"unknown","quiver":"unknown","collection":"unknown","http2":"unknown","mime":"unknown","stream_channel":"unknown","typed_data":"unknown","colorama":"unknown","connectivity_wrapper":"unknown","convert":"unknown","crypto":"unknown","source_gen":"unknown","cookie_jar":"unknown","dio":"unknown","dio_cookie_manager":"unknown","cross_file":"unknown","device_info":"unknown","flutter_plugin_android_lifecycle":"unknown","image_picker_for_web":"unknown","image_picker_platform_interface":"unknown","package_info":"unknown","path_provider":"unknown","path_provider_linux":"unknown","path_provider_macos":"unknown","path_provider_windows":"unknown","plugin_platform_interface":"unknown","share":"unknown","shared_preferences":"unknown","shared_preferences_linux":"unknown","shared_preferences_macos":"u
D/Sentry  (18746): Serializing object: {"sid":"86d754cd-086f-4869-8c84-35ff012144b","did":"f0fb19f6-2e65-4681-ab8e-ee65291222f","started":"2021-10-20T13:39:35.701Z","status":"ok","seq":1634737414173,"errors":3,"timestamp":"2021-10-20T13:43:34.173Z","attrs":{"release":"app@2.214.01","environment":"debug"}}

**Comment by adam1929** [comment]
Hi @maxim-ivanchuk-idf, does this issue still occuring? Could be please write more details? Thank you
