### ISSUE TITLE
Retrieve Customer Segments

### ISSUE THREAD

**Issue by LarssK-TS** [exponea/exponea-flutter-sdk#30]
Sorry for asking this isn't really a troubleshooting issue. I am trying to find a way to get segment data for specific customers. I cannot see anything in the package, does the package include a method to do this or will I need to call the API following these guides?
https://documentation.bloomreach.com/engagement/reference/segmentations-2 
https://documentation.bloomreach.com/engagement/reference/customer-segmentations-test

Thanks

**Comment by adam1929** [comment]
Hi @LarssK-TS Flutter SDK has no API for Segmentations data yet. It is planned to bring support in future. I'm not able to tell ETA but please ask your CMS or contact support for more informations.
