### ISSUE TITLE
Not build on Android 12

### ISSUE THREAD

**Issue by aleksandr-kopenkov-idf** [exponea/exponea-flutter-sdk#4]
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1499777544.tmp/base.apk (at Binary XML file line #253): com.exponea.sdk.services.ExponeaFirebaseMessageService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present] (https://developer.android.com/about/versions/12/behavior-changes-12#exported)

**Comment by maxim-gapeenko-idf** [comment]
@michaela-dev are you planning to fix exponea-flutter for android 12+?

**Comment by michaela-dev** [comment]
@maxim-gapeenko-idf Yes, the first non-beta release is planned for March, and it will contain changes regarding Android 12.

**Comment by larsoleheggland** [comment]
> @maxim-gapeenko-idf Yes, the first non-beta release is planned for March, and it will contain changes regarding Android 12.

Is the first non-beta release still planned for March?

**Comment by michaela-dev** [comment]
Yes, finishing touches are in progress. I will let you know in this issue, when it is ready

**Comment by michaela-dev** [comment]
The new release is ready. Just make sure to check version update documentation, some changes may be required from your app side: https://github.com/exponea/exponea-flutter-sdk/blob/1.0.0/documentation/VERSION_UPDATE.md
