### ISSUE TITLE
Update IOS SDK

### ISSUE THREAD

**Issue by aleksandr-kopenkov-idf** [exponea/exponea-flutter-sdk#7]
Hi! Please update IOS SDK. The current flutter sdk has a problem https://github.com/exponea/exponea-ios-sdk/issues/37

**Comment by artem-stefanovich-idf** [comment]
Hi! The same problem.

**Comment by evgeniy-maksimovich-idf** [comment]
Hi, I have the same problem

**Comment by evgeniy-dudar-idf** [comment]
Hello! I also have this problem. Update needed...

**Comment by SaleemFlatCircle** [comment]
Ran into this problem. The dependency just needs updating

**Comment by xcibik00** [comment]
Hello everyone,
Fix for this will be a part of the new Exponea Flutter SDK version.
Based on the latest release timeline, it should be in the first half of Q1
We appreciate your patience.

**Comment by xcibik00** [comment]
Hello everyone,
I would like to inform you that new Flutter v1.2.0 is already released also with fix of this issue.
Thanks for your patience
