### ISSUE TITLE
iOS build fails

### ISSUE THREAD

**Issue by pantelistsakoulis-ts** [exponea/exponea-flutter-sdk#8]
Trying to build for iOS with the version of the plugin 1.1.0 fails due to the following error

ExponeaSDK/ExponeaSDK/ExponeaSDK/Classes/InAppMessages/View/InAppMessageWebView.swift:91:24
Swift Compiler Error (Xcode): 'isElementFullscreenEnabled' is only available in iOS 15.4 or newer

```swift
if #available(iOS 15.0, *) { <- This is the if statement that causes the issue
    preferences.isElementFullscreenEnabled = false
}
```

Changing this to 15.4, solves the problem and I was able to build.

On the newest iOS SDK version this problem seems to be solved, so maybe an update to the native SDKs will be sufficient

**Comment by xcibik00** [comment]
Hi @pantelistsakoulis-ts, as mentioned https://github.com/exponea/exponea-flutter-sdk/issues/7 
We are working on the update, this will be fixed in new Flutter SDK version.
Thank you for your patience
